# Generated by Django 6.0.6 on 2026-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_year', models.CharField(max_length=6)),
                ('semester', models.CharField(max_length=1)),
                ('armi_category', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('total_applications', models.IntegerField()),
                ('avg_matric_prob', models.FloatField()),
                ('expected_matriculations', models.FloatField()),
                ('week_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controlled', models.CharField(max_length=1)),
            ],
        ),
    ]
