# Generated by Django 6.0.6 on 2026-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='entry_year',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='week_num',
        ),
        migrations.AddField(
            model_name='forecast',
            name='faculty_name',
            field=models.CharField(default='Unknown', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='fee_status',
            field=models.CharField(default='Unknown', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='snapshot_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
