# Generated by Django 6.0.6 on 2026-07-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVis', '0003_alter_forecast_text_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('algorithm', models.CharField(max_length=50)),
                ('calibration', models.CharField(max_length=50)),
                ('training_years', models.CharField(max_length=25)),
                ('training_semesters', models.CharField(max_length=25)),
                ('test_period', models.CharField(max_length=25)),
                ('roc_auc', models.FloatField()),
                ('brier', models.FloatField()),
                ('created', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='dataVis.forecastmodel'),
        ),
    ]
