# Generated by Django 6.0.6 on 2026-07-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVis', '0004_forecastmodel_forecast_forecast_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='dataVis.forecastmodel'),
            preserve_default=False,
        ),
    ]
